config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: 'items#index'

  resources :users, only: [:index, :show, :edit, :update, :new]
  resources :credit_cards, only: [:new, :edit, :create, :show, :destroy] do
  end
  resource :item_payments do
    member do
      get  "buy"
      post "pay"
    end
  end

  resources :items do
    resources :comments, only: :create
    resources :item_images, only: [:new, :edit, :update]
    resources :brands, only: [:new, :edit, :update]
    resources :shipping, only: [:new, :edit, :update]
    member do
      get 'category_children' 
      get 'category_grandchildren'
    end
    collection do
      get 'category_children' 
      get 'category_grandchildren'
    end
  end

end

app/models/item_payment.rb
class ItemPayment < ApplicationRecord
  belongs_to                    :item
end

app/controllers/item_payments_controller.rb
class ItemPaymentsController < ApplicationController

  require "payjp"

  def buy
    @item = Item.find_by(id: params[:format])
    @images = @item.item_images.all
    if user_signed_in?
      @user = current_user
      if @user.credit_card.present?
        Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
        @card = CreditCard.find_by(user_id: current_user.id)
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @customer_card = customer.cards.retrieve(@card.card_id)

        @card_brand = @customer_card.brand
        case @card_brand
        when "Visa"
          @card_src = "visa.svg"
        when "JCB"
          @card_src = "jcb.svg"
        when "MasterCard"
          @card_src = "master.svg"
        when "American Express"
          @card_src = "amex.svg"
        when "Diners Club"
          @card_src = "diners.svg"
        when "Discover"
          @card_src = "discover.svg"
        end

        @exp_month = @customer_card.exp_month.to_s
        @exp_year = @customer_card.exp_year.to_s.slice(2,3)
      else
        
      end
    else
      redirect_to user_session_path, alert: "ログインしてください"
    end
  end

  def pay
    @item = Item.find(params[:item_id])
    @images = @item.item_images.all

    if @item.buyer_id.present?
      redirect_to item_path(@item.id), alert: "売り切れています。"
    else
        @item.with_lock do
        if current_user.credit_card.present?
          @card = CreditCard.find_by(user_id: current_user.id)
          Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
          charge = Payjp::Charge.create(
          amount: @item.price,
          customer: Payjp::Customer.retrieve(@card.customer_id),
          currency: 'jpy'
          )
          @item.buyer_id = current_user.id
          redirect_to root_path
        else
          Payjp::Charge.create(
          amount: @item.price,
          card: params['payjp-token'],
          currency: 'jpy'
          )
          @item.buyer_id = current_user.id
        end
        @item_payment = ItemPayment.create(buyer_id: current_user.id, item_id: params[:item_id])
        @item.update(buyer_id: current_user.id)
        @item.save!
      end
    end
  end
  

    private
  
    def item_params
      params.require(:item).merge(buyer_id: current_user.id)
    end
  
end

app/helpers/item_payment_helper.rb
module ItemPaymentHelper
end

app/views/item_payments/buy.html.haml
%link{href: "item_payment.scss", rel: "stylesheet"}

.container
  %header.header-area
    %h1.header-area__title
      .image__box__top
  %main.main
    %section.buy
      %h2.buy__head
        購入内容の確認
      %section.buy__item
        .buy__item__content
          .buy__item__content__box
            %h3.buy__item__content__box__image
              - @item.item_images.each.with_index do |image, i|
                -if i == 0
                  = image_tag "#{image.image}", alt: '商品画像', width: '150', height: '100', class: 'image-first', index: i
            .buy__item__content__detail
              %p.buy__item__content__detail__name
                = @item.item_name
              %p.buy__item__content__detail__price
                %span
                  = "#{@item.price}" + "円"
                %span.shipping-fee
                  （税込）送料込み
      %section.buy__item
        .buy__item__content
          %section.buy__item__content__method.buy-user-info
          - if @user.credit_card.present?
            .purchase_function
              .credit_card_info_title
                クレジットカード情報
                .credit_card_info
                  .credit_card_info__brand
                    = image_tag "cards/#{@card_src}", size: "49x20", class: "credit_card_info__brand__img", alt: @card_brand
                  .credit_card_info__numbers
                    .number
                      = "**** **** **** " + @customer_card.last4
                    .expiration_date
                      .expiration_date__title
                        有効期限
                      .expiration_date__info
                        = @exp_month + " / " + @exp_year
              .purchase_function__btn
                = link_to "登録クレジットカードで購入する", pay_item_payments_path(item_id: @item.id), method: :post, class: "btn"
          - else 
            .purchase_none_btn
              = link_to "クレジットカードを登録してください", edit_credit_card_path(current_user.id)
  %footer.footer-area
    %nav.footer-area__content
      %ul.clearfix.footer-area__content__box
        %li
          = link_to "プライバシーポリシー", "#", class: "footer-area__content__box__element"
        %li
          = link_to "フリマ利用規約", "#", class: "footer-area__content__box__element"
        %li
          = link_to "特定商取引に関する表記", "#", class: "footer-area__content__box__element"
    = link_to image_tag('logo-white.png', alt: "furima", width: "230", height: "65" ), "#"
    %p
      %small
        © Furima, Inc.

app/views/item_payments/pay.html.haml
.pay
  .main_contents
    .main_details
      .main_details__message
        購入が完了しました。
    -# # 商品の表示を部分テンプレートで共通化
    -# # 今回の実装にはあまり関係ないので省略
    -# = render "purchases/shared/purchase_product_info.html.haml", product: @product, images: @images
    %ul.purchased__links
      %li.purchased__links__TopPage
        = link_to "トップページに戻る", root_path, class: "purchased__links__TopPage__btn"
      %li.purchased__links__index
        = link_to "購入商品一覧", "#", class: "purchased__links__index__btn"