config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: 'items#index'

  resources :users, only: [:index, :show, :edit, :update, :new]
  resources :credit_cards, only: [:new, :edit, :create, :show, :destroy] do
  end
  resource :item_payments do
    member do
      get  "buy"
      post "pay"
    end
  end

  resources :items do
    resources :comments, only: :create
    resources :item_images, only: [:new, :edit, :update]
    resources :brands, only: [:new, :edit, :update]
    resources :shipping, only: [:new, :edit, :update]
    member do
      get 'category_children' 
      get 'category_grandchildren'
    end
    collection do
      get 'category_children' 
      get 'category_grandchildren'
    end
  end

end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user, optional: true
  validates  :customer_id, :card_id, presence: true
  
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  require "payjp"

  def new
    @card = CreditCard.where(user_id: current_user.id)
    redirect_to credit_card_path(current_user.id) if @card.exists?
  end

  def create
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

    if params["payjp_token"].blank?
      redirect_to action: "new", alert: "クレジットカードを登録できませんでした。"
    else
      customer = Payjp::Customer.create(
        card: params["payjp_token"],
        metadata: {user_id: current_user.id} 
      )
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to user_path(current_user.id)
      else
        redirect_to action: "create"
      end
    end
  end

  def show
    @card = CreditCard.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)

      @card_brand = @customer_card.brand
      case @card_brand
      when "Visa"
        @card_src = "visa.svg"
      when "JCB"
        @card_src = "jcb.svg"
      when "MasterCard"
        @card_src = "master.svg"
      when "American Express"
        @card_src = "amex.svg"
      when "Diners Club"
        @card_src = "diners.svg"
      when "Discover"
        @card_src = "discover.svg"
      end

      @exp_month = @customer_card.exp_month.to_s
      @exp_year = @customer_card.exp_year.to_s.slice(2,3)
    end
  end

  def destroy
    @card = CreditCard.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      if @card.destroy
      else
        redirect_to credit_card_path(current_user.id), alert: "削除できませんでした。"
      end
    end

  def edit
  end

end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_side_bar.haml
.conteiner__side
  %nav.conteiner__side__nav
    %ul.conteiner__side__nav__list
      %li.conteiner__side__nav__list__item
        = link_to user_path(current_user.id) do
          マイページ
      %li.conteiner__side__nav__list__item
        = link_to new_item_path(current_user.id) do
          出品する
      %li.conteiner__side__nav__list__item
        = link_to  do
          出品した商品ー出品中
      %li.conteiner__side__nav__list__item
        = link_to  do
          出品した商品ー取引中 
      %li.conteiner__side__nav__list__item
        = link_to  do
          出品した商品ー売却済み
      %li.conteiner__side__nav__list__item
        = link_to  do
          購入した商品ー取引中
      %li.conteiner__side__nav__list__item
        = link_to  do
          購入した商品ー過去の取引
    %h3.conteiner__side__nav__head
      設定
    %ul.conteiner__side__nav__list
      %li.conteiner__side__nav__list__item
        = link_to  do
          プロフィール
      %li.conteiner__side__nav__list__item
        = link_to  do
          発送元・お届け先住所変更
      %li.conteiner__side__nav__list__item
        = link_to edit_credit_card_path(current_user.id) do
          支払い方法
      %li.conteiner__side__nav__list__item
        = link_to  do
          メール/パスワード
      %li.conteiner__side__nav__list__item
        = link_to  do
          本人情報
      %li.conteiner__side__nav__list__item
        = link_to  do
          電話番号の確認
      %li.conteiner__side__nav__list__item
        = link_to edit_user_path(current_user.id) do
          ログアウト

app/views/credit_cards/destroy.html.haml
.destoroy
  .destoroy__frame
    .destoroy__frame__message
      削除が完了しました。
    %ul.destoroy__frame__btns
      %li.credit_card_new_link
        = link_to "クレジットカード新規登録", new_credit_card_path, class: "credit_card_new_link__btn"
      %li.my_page_link
        = link_to "マイページに戻る", users_path(current_user.id), class: "my_page_link__btn"

app/views/credit_cards/edit.html.haml
.conteiner
  = render "side_bar"  
  .conteiner__contents
    %h2.conteiner__contents__head
      支払い方法
    .conteiner__contents__chapter
      .conteiner__contents__chapter__inner
        %section
          .conteiner__contents__chapter__inner__single
            %h3.conteiner__contents__chapter__inner__single__head
              クレジットカード一覧
          %ul.conteiner__contents__chapter__inner__single__payment-list
        %section.conteiner__contents__chapter__inner__credit
          %button.conteiner__contents__chapter__inner__credit__button
            = link_to "クレジットカードを追加する", new_credit_card_path, method: :get ,class: ".conteiner__contents__chapter__inner__credit__button"              
        .conteiner__contents__chapter__inner__settings
          %span
            支払い方法について  ＞

app/views/credit_cards/new.html.haml
.conteiner
  = render "side_bar"
  .content
    %section.chapter-container
      %h2.head クレジットカード情報入力
      .add-card
        = form_tag(credit_cards_path, method: :post, id: "charge-form", class: "details", name: "inputForm") do
          .add-card
            .add-card__number-details
              .add-card__number-details__card-number カード番号
              %span.add-card__number-details__must-check 必須
            .add-card__number
              = text_field_tag 'payment_card_no', "", class: 'add-card__number__cardnumber', id: "payment_card_no", placeholder: '半角数字のみ', type: "text", maxlength: "16"
            .image
              = image_tag(image_path('cards/visa.svg'), class: 'visa', size: "49x20")
              = image_tag(image_path('cards/master.svg'), class: 'master', size: "49x20")
              = image_tag(image_path('cards/jcb.svg'), class: 'jcb', size: "49x20")
              = image_tag(image_path('cards/amex.svg'), class: 'amex', size: "49x20")
              = image_tag(image_path('cards/diners.svg'), class: 'diners', size: "49x20")
              = image_tag(image_path('cards/discover.svg'), class: 'discover', size: "49x20")
            .add-card__expirationdate
              .add-card__expirationdate__details
                .add-card__expirationdate__details__date 有効期限
                %span.add-card__expirationdate__details__must-check 必須
              .add-card__expirationdate__choice
                .add-card__expirationdate__choice__month
                  %select#payment_card_month.card-default{name: "payment_card_month", type: "text"}
                    %option{value: "1"} 01
                    %option{value: "2"} 02
                    %option{value: "3"} 03
                    %option{value: "4"} 04
                    %option{value: "5"} 05
                    %option{value: "6"} 06
                    %option{value: "7"} 07
                    %option{value: "8"} 08
                    %option{value: "9"} 09
                    %option{value: "10"} 10
                    %option{value: "11"} 11
                    %option{value: "12"} 12
                  .month-details 月
                .add-card__expirationdate__choice__year
                  %select#payment_card_year.card-default{name: "payment_card_year", type: "text"}
                    %option{value: "2020"} 20
                    %option{value: "2021"} 21
                    %option{value: "2022"} 22
                    %option{value: "2023"} 23
                    %option{value: "2024"} 24
                    %option{value: "2025"} 25
                    %option{value: "2026"} 26
                    %option{value: "2027"} 27
                    %option{value: "2028"} 28
                    %option{value: "2029"} 29
                    %option{value: "2030"} 30
                  .year-details 年
            .add-card__securitycode
              .add-card__securitycode__details
                .add-card__securitycode__details__title セキュリティコード
                %span.must_check 必須
              .add-card__securitycode__cardsecurity
                = text_field_tag  "payment_card_cvc", "", type: 'text', class: 'add-card__securitycode__cardsecurity__form', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面4桁もしくは3桁の番号'
              .add-card__securitycode__card-question カード裏面の番号とは？
            .add 
              = submit_tag "登録する", class: "add__btn", id: "payment_card_submit-button" 

app/views/credit_cards/show.html.haml
.show
  .show__frame
    .show__frame__title
      登録クレジットカード情報
    .credit_card__list
      .credit_card__list__title
        クレジットカード一覧
      .credit_card__list__frame
        .credit_card_info
          .credit_card_info__brand
            = image_tag "cards/#{@card_src}", class: "credit_card_info__brand__img", alt: @card_brand, size: "49x20"
          .credit_card_info__numbers
            .number
              = "**** **** **** " + @customer_card.last4
            .expiration_date
              .expiration_date__title
                有効期限
              .expiration_date__info
                = @exp_month + " / " + @exp_year
        .destroy__function
          .destroy__function__link
            = link_to credit_card_path, method: :delete, class: "destroy__function__link__btn" do 
              削除する
      .payment-details
        = link_to "支払い方法について >", "", class: "payment-details__btn"