config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: 'items#index'

  resources :users, only: [:index, :show, :edit, :update, :new]
  resources :credit_cards, only: [:new, :edit, :create, :show, :destroy] do
  end
  resource :item_payments do
    member do
      get  "buy"
      post "pay"
    end
  end

  resources :items do
    resources :comments, only: :create
    resources :item_images, only: [:new, :edit, :update]
    resources :brands, only: [:new, :edit, :update]
    resources :shipping, only: [:new, :edit, :update]
    member do
      get 'category_children' 
      get 'category_grandchildren'
    end
    collection do
      get 'category_children' 
      get 'category_grandchildren'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :nickname, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX } 
  validates :password, confirmation: true, presence: true, length: { minimum: 7 }
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :birthdate, presence: true
  validates :phone, presence: true, length: { in: 10..11 }

  has_one :address
  has_one :credit_card, dependent: :destroy

  has_many :credits
  has_many :items
  has_many :comments

  has_many :buyed_items, foreign_key: "buyer_id"
  has_many :saling_items, -> { where("buyer_id is NULL") }, foreign_key: "saler_id"
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "saler_id"

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
  end

  protected

  def address_params
    params.require(:address).permit(:zipcode, :address, :city, :prefecture_id, :building)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_user

def show
  # user = User.find(params[:id])
end

# private
#   def require_user
#     raise Forbidden unless current_user
#   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side_bar.haml
.conteiner__side
  %nav.conteiner__side__nav
    %ul.conteiner__side__nav__list
      %li.conteiner__side__nav__list__item
        = link_to user_path(current_user.id) do
          マイページ
      %li.conteiner__side__nav__list__item
        = link_to new_item_path(current_user.id) do
          出品する
      %li.conteiner__side__nav__list__item
        = link_to  do
          出品した商品ー出品中
      %li.conteiner__side__nav__list__item
        = link_to  do
          出品した商品ー取引中 
      %li.conteiner__side__nav__list__item
        = link_to  do
          出品した商品ー売却済み
      %li.conteiner__side__nav__list__item
        = link_to  do
          購入した商品ー取引中
      %li.conteiner__side__nav__list__item
        = link_to  do
          購入した商品ー過去の取引
    %h3.conteiner__side__nav__head
      設定
    %ul.conteiner__side__nav__list
      %li.conteiner__side__nav__list__item
        = link_to  do
          プロフィール
      %li.conteiner__side__nav__list__item
        = link_to  do
          発送元・お届け先住所変更
      %li.conteiner__side__nav__list__item
        = link_to edit_credit_card_path(current_user.id) do
          支払い方法
      %li.conteiner__side__nav__list__item
        = link_to  do
          メール/パスワード
      %li.conteiner__side__nav__list__item
        = link_to  do
          本人情報
      %li.conteiner__side__nav__list__item
        = link_to  do
          電話番号の確認
      %li.conteiner__side__nav__list__item
        = link_to edit_user_path(current_user.id) do
          ログアウト

app/views/users/edit.html.haml
.conteiner
  = render "side_bar"
  .conteiner__content
    .conteiner__content__chapter
      .conteiner__content__chapter__inner
        .conteiner__content__chapter__inner__logout
          %button.conteiner__content__chapter__inner__logout__button
            = button_to "ログアウト", destroy_user_session_path, method: :delete ,class: "conteiner__content__chapter__inner__logout__button"
            

app/views/users/show.html.haml
.conteiner
  = render "side_bar"
  .conteiner__content
    .conteiner__content__user-icon
      = link_to do
        .conteiner__content__user-icon__img
          
        %h2.conteiner__content__user-icon__name
          = current_user.nickname
          .conteiner__content__user-icon__number
          評価 0  出品数 0
    .conteiner__content__tab
      %h2.conteiner__content__tab__head
        購入した商品
      %ul.conteiner__content__tab__tabs
        %li<
          %h3
            取引中
        %li<
          %h3
            過去の取引
      %ul.conteiner__content__tab__content
        %li<
          取引中の商品がありません