config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: 'items#index'

  resources :users, only: [:index, :show, :edit, :update, :new]
  resources :credit_cards, only: [:new, :edit, :create, :show, :destroy] do
  end
  resource :item_payments do
    member do
      get  "buy"
      post "pay"
    end
  end

  resources :items do
    resources :comments, only: :create
    resources :item_images, only: [:new, :edit, :update]
    resources :brands, only: [:new, :edit, :update]
    resources :shipping, only: [:new, :edit, :update]
    member do
      get 'category_children' 
      get 'category_grandchildren'
    end
    collection do
      get 'category_children' 
      get 'category_grandchildren'
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :category, optional: true
  belongs_to :brand, optional: true
  accepts_nested_attributes_for :brand, allow_destroy: true
  belongs_to :shipping, optional: true
  accepts_nested_attributes_for :shipping, allow_destroy: true
  has_many :item_images
  accepts_nested_attributes_for :item_images, allow_destroy: true
  has_many :comments
  belongs_to                    :saler,       optional: true
  belongs_to                    :buyer,       optional: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :status
  belongs_to :prefecture

  validates :item_name, presence: true
  validates :item_images, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  validates :content, presence: true
  validates :category_id, presence: true
  validates :user_id, presence: true
  validates :status_id, presence: true



end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_item,    only: [:show, :edit, :update, :destroy]

  def index
    @item = Item.includes(:item_images, :brands, :shippings).order('created_at DESC')
    @newItems = Item.includes(:item_images).where(buyer_id: nil).limit(3)
    @item = Item.new
    @brand = Brand.new

  end

  def new
    @item = Item.new
    @item.item_images.build
    @brand = Brand.new
    @shipping = Shipping.new
    @category = Category.where(ancestry: nil)
  end

  def category_children  
    @category_children = Category.find(params[:productcategory]).children 
  end
  
  def category_grandchildren
    @category_grandchildren = Category.find(params[:productcategory]).children
  end

  def create
    @item = Item.new(item_params)
    @brand = Brand.new(brand_params)
    @shipping = Shipping.new(shipping_params)

    if @item.save
      item_id = @item.id
      @brand = Brand.new(brand_params.merge(item_id: item_id))
      @shipping = Shipping.new(shipping_params.merge(item_id: item_id)) 
      if  @brand.save && @shipping.save
        @item.brand_id = @brand.id
        @item.shipping_id = @shipping.id
        @item.save 
        redirect_to root_path
      else
        redirect_to new_item_path(current_user.id)  
      end
    else
      redirect_to new_item_path(current_user.id)
    end
  end 

  def show
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def edit
    @item.item_images.build
    @categories = @item.category
    @brand = @item.brand
    @shipping = @item.shipping
    
    grandchild_category = @item.category
    child_category = grandchild_category.parent


    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
  end

  def update
    @item = Item.find(params[:id])
    @brand = @item.brand
    @shipping = @item.shipping
    if @item.update(item_params) && @shipping.update(shipping_params) == @brand.update(brand_params)
      redirect_to root_path , notice: '出品情報が更新されました'
    else
      @categories = @item.category
      grandchild_category = @item.category
      child_category = grandchild_category.parent

      @category_parent_array = []
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent
      end

      @category_children_array = []
      Category.where(ancestry: child_category.ancestry).each do |children|
        @category_children_array << children
      end

      @category_grandchildren_array = []
      Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
        @category_grandchildren_array << grandchildren
      end
      redirect_to edit_item_path
    end
  end
  

  private

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end

    def item_params
      params.require(:item).permit(:brand_id, :shipping_id, :item_name, :price, :size, :content, :category_id, :status_id, :buyer_id, item_images_attributes: [:image, :id, :_destroy]).merge(user_id: current_user.id, saler_id: current_user.id)
    end   

    def brand_params  
      params.require(:brand).permit(:brand)
    end

    def shipping_params  
      params.require(:shipping).permit(:ship_base_id, :ship_method, :ship_date_id, :prefecture_id)
    end

    def set_item
      @item = Item.find(params[:id])
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
.title
  = link_to image_tag("logo.png", height: '49', width: '185', class: 'logo'), "/"
.content
  .content-main
    = form_with url:item_path(@item), method: :patch, local: true do |f|
      .image-product
        %label.label-edit 出品画像
        %sapn.required 必須
        %p 最大１０枚までアップロードできます。
        .name__image
          .name__image__set
            = f.fields_for @item do |item|
              #image-box__square
                #previews
                  - @item.item_images.each_with_index do |item_image, index|
                    - if item_image.image.url
                      %div{data: {index: "#{index}"}, id: "previews__var"}
                        = image_tag item_image.image.url, data: { index: "#{index}" }, width: "114px", height: '80px' 
                        %span.js-remove 削除
                = item.fields_for :item_images do |item_image|
                  %div{data: {index: "#{item_image.index}"}, class: "js-file_group"}
                    = item_image.file_field :image, style: "display:none", class: 'js-file'
                  - if item_image.object.persisted? 
                    = item_image.check_box :_destroy, style: "display:none", data:{ index: item_image.index }, class: 'hidden-destroy'
                #image-box__square__var
                  %label{for: "_item_item_images_attributes_#{@item.item_images.count}_image"}
                    %i.fas.fa-camera
              %p
                ドラッグアンドドロップ
                %br
                またはクリックしてファイルをアップロード
        .image__message
          画像がありません
      .item-explain
        %label.label-edit 商品名
        %sapn.required 必須
        .item-explain__text
          = f.fields_for @item do |item|
            = item.text_field :item_name, class: "item-explain__text__form", placeholder: "40文字まで"
          %p 
            入力してください
          %label.label-edit 商品の説明
          %sapn.required 必須
          .item-explain__text__textarea
            = f.fields_for @item do |item|
              = item.text_area :content, placeholder: "商品の説明（必須 1,000文字以内）\n（色、素材、重さ、定価、注意点など）\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありませ\nん。あわせやすいのでおすすめです。"
          %p
            入力してください
            .product_select-details
              .product_select-group
                %label.label-edit  カテゴリー
                %sapn.required 必須
              .product_category-select
                = f.select :parent_id, options_for_select(@category_parent_array.map{|b| [b.title, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @item.category.parent.parent.id}),{}, {class: 'category_select-box', id: 'category_select'}
                %i.fa.fa-chevron-down
              .product_select-children
                .product-select-wrapper#children_wrapper
                  .product_category-select
                    = f.select :child_id, options_for_select(@category_children_array.map{|b| [b.title, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @item.category.parent.id}),{}, {class: 'category_select-box', id: 'child_category'}
                  .product_select-grandchildren
                    .product-select-wrapper#grandchildren_wrapper
                      .product_category-select
                        = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.title, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @item.category.id}),{}, {class: 'category_select-box', id: 'grandchild_category', name: 'item[category_id]'}
                      .product_select-grandchildren


                -# .wrapper.category-wrapper
                -#   = f.label :category_id , class: 'wrapper__label category-wrapper-label', id: "wrapper__label--category" do
                -#     .category-wrapper-box
                -#       .category-wrapper-select
                -#         .category-wrapper-select__box
                -#           = f.select :parent_name, @category_parent_array, {selected:@item.category.parent.parent.title}, { class: 'category-wrapper__category form-control', id: 'parent_category'}
                -#       .category-wrapper-select#children_wrapper
                -#         .category-wrapper-select__box
                -#           = f.select :child_id, options_for_select(@category_children_array.map{|b| [b.title, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @item.category.parent.id}),{}, {class: 'category-wrapper__category form-control', id: 'child_category'}
                -#       .category-wrapper-select#grandchildren_wrapper
                -#         .category-wrapper-select__box
                -#           = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.title, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @item.category.id}),{}, {class: 'category-wrapper__category form-control', id: 'grandchild_category'}

              -# .product_category-select
              -# = f.fields_for @item do |item|
              -#   = f.collection_select :category, Category.where(ancestry: nil), :id, :title, { prompt: "選択してください" }, { class: "category_select-box", id: "category_select" }
              -#   %i.fa.fa-chevron-down
              -# .product_select-children
      .item-show__list
        %label.label-edit  ブランド
        %sapn.item-show__list__any 任意
        = f.fields_for @brand do |brand|
          = brand.text_field :brand, placeholder: "例） シャネル"
        .choice
          選択してください
      .item-show__list
        %label.label-edit 商品の状態
        %sapn.required 必須
        = f.fields_for @item do |item|
          = item.collection_select :status_id, Status.all, :id, :name, prompt: "選択してください", class: 'input'
        .choice
          選択してください
      .delivery
        %p 
          配送について
        .delivery__list
          %label.label-edit  配送料の負担
          %sapn.required 必須
          = f.fields_for @shipping do |shipping|
            = shipping.collection_select :ship_base_id, ShipBase.all, :id, :name, prompt: "選択してください", class: 'input'
            .choice
              選択してください
            .delivery__list
              = shipping.label :発送元の地域, {class: 'label-edit'}
              = shipping.label :必須, {class: 'required'}
              .delivery__list__prefecture
                = shipping.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "選択してください", class: 'input'
            .choice
              選択してください
            .delivery__list
              %label.label-edit  発送までの日数
              %sapn.required 必須
              = shipping.collection_select :ship_date_id, ShipDate.all, :id, :name, prompt: "選択してください", class: 'input'
              .choice
                選択してください
      .item-price
        %p
          価格（¥300〜9,999,999)
        .item-price__content
          .item-price__bye
            %span ¥
            = f.fields_for @item do |item|
              = item.text_field :price, placeholder: "0"
        -# %p.form-error
        -#   300以上9999999以下で入力してください
      .size-area
        .item-size
          %p
            サイズ(S~L等)
          .item-size__content
            .item-size__status
              %sapn.required 必須
            .item-size__bye
              %span 
              = f.fields_for @item do |item|
                = item.text_field :size, placeholder: "S~L等"
      -# .fee
      -#   .fee__price
      -#     販売手数料 (10%)
      -#   .fee__content
      -#     %span ー
      -# .profit
      -#   .profit__price
      -#     販売利益
      -#   .profit__content
      -#     %span ー
      .exhibilion
        .exhibilion__button
          = f.submit "変更する", class: 'exhibilionbutton'
          %button{type: "submit", class: 'exhibilion__save'} 下書きに保存
        %a.top__return 
          もどる
        %p.warning
          禁止されている
          %a 行為 および
          %a 出品物
          を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律に
          より処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  .product__footer
    .product__footer__link
      = link_to 'プライバシーポリシー', '/', class: 'footer-link'
      = link_to 'フリマ利用規約', '/', class: 'footer-link'
      = link_to '特定商取引に関する表記', '/', class: 'footer-link'
    .product__footer__logo
      = image_tag 'logo-white.png', height: '49', width: '185'
    %p.logo__tag
      © FURIMA, Inc.

app/views/items/index.html.haml
.main__one
  .main__one__content
    %h.main__one__content__subtitle
      %br
      人生を変えるフリマアプリ

    %p.content__text
      FURIMAはだれでもかんたんに出品・購入できる
      %br
      フリマアプリです
    .content__btn
      = link_to image_tag("http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", size: "150x80"), "#"
      = link_to image_tag("http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", size: "150x80"), "#"

.main__two
  %b.main__two__title
    FURIMAが選ばれる3つの理由
  %ul.photo__series
    %li.photo__one
      .photo__one__picture
        = image_tag "pict-reason-01.jpg", size: "300x300"
      %b
        ３分 ですぐに出品
      %p
        スマホで入力するだけで簡単に出品で
      %p
        きる！
    %li.photo__two
      .photo__two__picture
        = image_tag "pict-reason-02.jpg", size: "300x300"
      %b
        シンプル で使いやすい
      %p
        めんどくさい入力は必要なく、検索も
      %p
        購入もスムーズ！
    %li.photo__three
      .photo__three__picture
        = image_tag "pict-reason-03.jpg", size: "300x300"
      %b
        手数料 業界最安
      %p
        最大３％でお得に出品＆購入！

.main__three
  .main__three__content
    %h.main__three__content__subtitle
      会員数日本一位

    %p.content__text
      FURIMAはだれでもかんたんに出品・購入できる
      %br
      フリマアプリです
    .content__btn
      = link_to image_tag("http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", size: "150x80"), "#"
      = link_to image_tag("http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", size: "150x80"), "#"


.main__four
  %b.main__four__title
    FURIMAの特徴
  %ul.photo__series__secound
    %li.photo__four
      .photo__four__picture
        = image_tag "icon-01.png", size: "300x300"
      %b
        簡単に売り買いできる
      %p
        スマホひとつで、いつでもどこでも簡単
      %p
        に出品・購入が可能！
    %li.photo__five
      .photo__five__picture
        = image_tag "icon-03.png", size: "300x300"
      %b
        売上金は即日振込みに対応
      %p
        午前９時までに振込みをご依頼いただけれ
      %p
        ば、翌日に指定の口座に入金いたします！
    %li.photo__six
      .photo__six__picture
        = image_tag "icon-04.png", size: "300x300"
      %b
        様々な支払いに対応
      %p
        お支払いは、クレジットカードだけでな
      %p
        く、ポイントや売上金など多彩な方法が
      %p
        あります。
  

.main__five
  .main__five__one
    %h2.head
      ピックアップカテゴリー

    .product__box
      .product__head
        %h3.title__one
          = link_to "新規投稿商品", "#"
      .product__lists
        .product__list
          - @newItems.each do |item|
            = link_to item_path(item), class: "list__image" do
              %figure.item__images
                = image_tag item.item_images[0].image.url, alt: "image_url",size: "200x150"
              .product__list__body
                %h3.name
                  = item.item_name
                .details
                  %ul
                    %li
                      = item.price
                      円
                  %p
                    (税込)
        
  .main__five__two
    %h2.head
      ピックアップブランド

    .product__box
      .product__head
        %h3.title__two
          = link_to "アーカイバ", "#"
      .product__lists
        .product__list
          - @newItems.each do |item|
            = link_to item_path(item), class: "list__image" do
              %figure.item__images
                = image_tag item.item_images[0].image.url, alt: "image_url",size: "200x150"
              .product__list__body
                %h3.name
                  = item.item_name
                .details
                  %ul
                    %li
                      = item.price
                      円
                  %p
                    (税込)

.banner
  .banner__inner
    %h.banner__inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.banner__inner__text
      今すぐ無料ダウンロード！
    .content__btn
    = link_to image_tag("http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", size: "150x80"), "#"
    = link_to image_tag("http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", size: "150x80"), "#"

app/views/items/new.html.haml
.title
  = link_to image_tag("logo.png", height: '49', width: '185', class: 'logo'), "/"
.content
  .content-main
    = form_with url: items_path, method: "POST", local: true do |f|
      .image-product
        %label.label-edit 出品画像
        %sapn.required 必須
        %p 最大１０枚までアップロードできます。
        .name__image
          .name__image__set
            .name__image__set__file.item-num-0
              = f.fields_for @item do |item|
                = item.fields_for :item_images do |item_image|
                  #image-box__container
                    = item_image.file_field :image, type: 'file', name: "item[item_images_attributes][0][image]", value:"", style: "display:none", id:"img-file0", class:"js-file"
                    #image-box__container__var
                      %label{for: "img-file0"}
                        %i.fas.fa-camera
            %p
              ドラッグアンドドロップ
              %br
              またはクリックしてファイルをアップロード
        .image__message
      .item-explain
        %label.label-edit 商品名
        %sapn.required 必須
        .item-explain__text
          = f.fields_for @item do |item|
            = item.text_field :item_name, class: "item-explain__text__form", placeholder: "40文字まで"
          %p 
            入力してください
          %label.label-edit 商品の説明
          %sapn.required 必須
          .item-explain__text__textarea
            = f.fields_for @item do |item|
              = item.text_area :content, placeholder: "商品の説明（必須 1,000文字以内）\n（色、素材、重さ、定価、注意点など）\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありませ\nん。あわせやすいのでおすすめです。"
          %p
            入力してください
            .product_select-details
              .product_select-group
                %label.label-edit  カテゴリー
                %sapn.required 必須
              .product_category-select
                = f.collection_select :category, Category.where(ancestry: nil), :id, :title, { prompt: "選択してください" }, { class: "category_select-box", id: "category_select" }
                %i.fa.fa-chevron-down
              .product_select-children
      .item-show__list
        %label.label-edit  ブランド
        %sapn.item-show__list__any 任意
        = f.fields_for @brand do |brand|
          = brand.text_field :brand, placeholder: "例） シャネル"
        .choice
          選択してください
      .item-show__list
        %label.label-edit 商品の状態
        %sapn.required 必須
        = f.fields_for @item do |item|
          = item.collection_select :status_id, Status.all, :id, :name, prompt: "選択してください", class: 'input'
        .choice
          選択してください
      .delivery
        %p 
          配送について
        .delivery__list
          %label.label-edit  配送料の負担
          %sapn.required 必須
          = f.fields_for @shipping do |shipping|
            = shipping.collection_select :ship_base_id, ShipBase.all, :id, :name, prompt: "選択してください", class: 'input'
            .choice
              選択してください
            .delivery__list
              = shipping.label :発送元の地域, {class: 'label-edit'}
              = shipping.label :必須, {class: 'required'}
              .delivery__list__prefecture
                = shipping.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "選択してください", class: 'input'
            .choice
              選択してください
            .delivery__list
              = shipping.label :発送日の目安, {class: 'label-edit'}
              = shipping.label :必須, {class: 'required'}
              .delivery__list__ship_date
                = shipping.collection_select :ship_date_id, ShipDate.all, :id, :name, prompt: "選択してください", class: 'input'
              .choice
                選択してください
      .item-price
        %p
          価格（¥300〜9,999,999)
        .item-price__content
          .item-price__bye
            %span ¥
            = f.fields_for @item do |item|
              = item.text_field :price, placeholder: "0"
        -# %p.form-error
        -#   300以上9999999以下で入力してください
      .size-area
        .item-size
          %p
            サイズ(S~L等)
          .item-size__content
            .item-size__status
              %sapn.required 必須
            .item-size__bye
              %span 
              = f.fields_for @item do |item|
                = item.text_field :size, placeholder: "S~L等"
        -# .fee
        -#   .fee__price
        -#     販売手数料 (10%)
        -#   .fee__content
        -#     %span ー
        -# .profit
        -#   .profit__price
        -#     販売利益
        -#   .profit__content
        -#     %span ー
      .exhibilion
        .exhibilion__button
          = f.submit "出品する", class: 'exhibilionbutton'
          %button{type: "submit", class: 'exhibilion__save'} 下書きに保存
        %a.top__return 
          もどる
        %p.warning
          禁止されている
          %a 行為 および
          %a 出品物
          を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律に
          より処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  .product__footer
    .product__footer__link
      = link_to 'プライバシーポリシー', '/', class: 'footer-link'
      = link_to 'フリマ利用規約', '/', class: 'footer-link'
      = link_to '特定商取引に関する表記', '/', class: 'footer-link'
    .product__footer__logo
      = image_tag 'logo-white.png', height: '49', width: '185'
    %p.logo__tag
      © FURIMA, Inc.

app/views/items/show.html.haml
.main
  .main__show
    .content__main
      .content__main__top
        .item-box
          %h2.item-box__title
            = @item.item_name
          .image__box__body
            .image__box__top
              - @item.item_images.each.with_index do |image, i|
                -if i == 0
                  = image_tag "#{image.image}", alt: '商品画像', class: 'image-first', index: i
            .image__box__list
              - @item.item_images.each.with_index do |image, i|
                - if i > 0 and i < 10
                  = image_tag "#{image.image}", width: '135', alt: '商品画像', index: i
          .item__box__price
            %span 
            = "￥#{@item.price}"
            .item__box__price__data
              %span (税込み)
              %span  送料込み
          - unless user_signed_in? && current_user.id == @item.user_id
            .item__box__payment
              = link_to buy_item_payments_path(@item.id) , class: "item_payment", method: :get do
                購入画面に進む
          .item__datail
            = @item.content
          .table
            %table.table__main
              %tbody.table__main__body
                %tr.table-tr
                  %th.table-th 出品者
                  %td.table-td 
                    = @item.user.nickname
                %tr.table-tr
                  %th.table-th カテゴリー
                  %td.table-td
                    = link_to "/", class: "link-blue" do
                      = @item.category.parent.parent.title
                      = @item.category.parent.title
                      = @item.category.title
                %tr.table-tr
                  %th.table-th ブランド
                  %td.table-td
                    = @item.brand.brand
                %tr.table-tr
                  %th.table-th 商品のサイズ
                  %td.table-td
                    = @item.size
                %tr.table-tr
                  %th.table-th 商品の状態
                  %td.table-td
                    = @item.status.name
                %tr.table-tr
                  %th.table-th 配送料の負担
                  %td.table-td 
                    = @item.shipping.ship_base.name
                %tr.table-tr
                  %th.table-th 発送元の地域
                  %td.table-td
                    = @item.shipping.prefecture.name
                %tr.table-tr
                  %th.table-th 発送日の目安
                  %td.table-td 
                    = @item.shipping.ship_date.name
          .optional__area
            %ul
              %li.optional__btn__star
                = icon('fa fa-star', class: 'star-icon')
                お気に入り 0
            %ul.optional
              %li.optional__btn__flag
                = link_to '/' do
                  = icon('fa fa-flag', class: 'flag')
                  不適切な商品の通報
          .fix-area
            - if user_signed_in? && current_user.id == @item.user_id 
              .fix-area__zone__edit
                = link_to "商品を編集する", "/items/#{@item.id}/edit", class: "item-edit"
            - if user_signed_in? && current_user.id == @item.user_id
              .fix-area__zone__delete
                = link_to "商品を削除する", "/items/#{@item.id}", method: "delete", class: "item-delete"
          .comment__contents
        .comment__box
          %ul.commentContents
          .form
            = form_with model: @comment, local: true do |f|
              = f.text_area :text, class: "comment__body"
            %P.notice
              相手のことを考えて丁寧なコメントを心がけましょう。
              %br
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %button.comment__button{name:'button', type: 'submit'}
              = icon('fa fa-comment', class: 'comment')
              コメントする
      %ul.links
        %li.links__left
          = link_to '#', class: 'links__left__icon' do
            = icon('fa fa-angle-left' ,class: 'angle-left')
            %sapn 前の商品
        %li.links__right
          = link_to '#', class: 'links__right__icon' do
            %sapn 後ろの商品
            = icon('fa fa-angle-right' ,class: 'angle-right')
      .items
        = link_to 'ベビー・キッズをもっと見る', '/posts/new',  class: 'items__show'